on:
  pull_request_target:
    types: ["labeled", "closed"]

jobs:
  backport:
    name: Backport PR
    runs-on: ubuntu-latest
    steps:
      - name: Backport Action
        uses: sqren/backport-github-action@debug-context
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          auto_backport_label_prefix: backport-to-

      - name: Info log
        if: ${{ success() }}
        run: cat /home/runner/.backport/backport.info.log 2>/dev/null
        
      - name: Debug log
        if: ${{ failure() }}
        run: cat /home/runner/.backport/backport.debug.log 2>/dev/null         
          
