on:
  pull_request_target:
    types: ["labeled", "closed"]

jobs:
  backport:
    name: Backport PR
    runs-on: ubuntu-latest
    steps:
      - name: Backport Action
        uses: sqren/backport-github-action@4cde6043d961fa14ae476077cb36ef2f00081fd9
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Info log
        if: ${{ success() }}
        run: cat /home/runner/.backport/backport.info.log
        
      - name: Debug log
        if: ${{ failure() }}
        run: cat /home/runner/.backport/backport.debug.log        
          
