name: Backport
on:
  pull_request:
    types:
      - closed
      - labeled

jobs:
  backport:
    runs-on: ubuntu-latest
    name: Backport Action
    steps:
      - name: Backport
        uses: sqren/backport-github-action@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
