name: Backport
on:
  pull_request:
    types:
      - closed
      - labeled

jobs:
  backport:
    runs-on: ubuntu-18.04
    name: Backport Action
    steps:
      - name: Backport
        id: backport
        uses: sqren/backport-github-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
      - name: Get the output time
        run: echo "The time was ${{ steps.backport.outputs.time }}"
